micronaut:
  application:
    name: clientcredentialsclientissue
  security:
    oauth2:
      clients:
        dependent-api-one:
          client-id: "apple"
          client-secret: "banana"
          grant-type: client_credentials
          token:
            url: "http://localhost:8080/dep1/auth" # see DependentApiOneController
            auth-method: client_secret_basic
          client-credentials:
            enabled: true
            uri-regex: "http://localhost:8080/dep1/resource.?"
    reject-not-found: false

